# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

# Builds ultralytics/yolov5:latest images on GitHub Actions runner

name: Build Docker Images

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  docker:
    if: github.repository == 'fjebari/yolov5'
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # copy full .git directory to access full git history in Docker images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build GPU image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: utils/docker/Dockerfile
          push: false  # Only build, do not push
          tags: ultralytics/yolov5:latest
