name: Build Docker Image

on:
  push:
    branches:
      - master  # Trigger on push to the main branch
  pull_request:
    branches:
      - master  # Trigger on PR to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specify OS for the action

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # The build context is the repository root
          file: ./utils/docker/Dockerfile  # Path to your Dockerfile
          push: false  # Don't push the image (unless you want to)
          tags: your-username/your-image:latest
          platforms: linux/amd64,linux/arm64  # Add other architectures if needed

      - name: Retrieve Image size and build time
        run: |
          docker image inspect your-username/your-image:latest --format='{{.Size}}'
