# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

# Builds ultralytics/yolov5:latest images on DockerHub https://hub.docker.com/r/ultralytics/yolov5

name: Build Docker Images

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  docker:
    if: github.repository == 'fjebari/yolov5'
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # copy full .git directory to access full git history in Docker images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login step is optional here, and it will only be needed if pushing to Docker Hub
      - name: Login to Docker Hub (optional)
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build arm64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          file: utils/docker/Dockerfile-arm64
          push: false  # Do not push to Docker Hub
          tags: ultralytics/yolov5:latest-arm64

      - name: Build CPU image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: utils/docker/Dockerfile-cpu
          push: false  # Do not push to Docker Hub
          tags: ultralytics/yolov5:latest-cpu

      - name: Build GPU image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: utils/docker/Dockerfile
          push: false  # Do not push to Docker Hub
          tags: ultralytics/yolov5:latest
